services:
  - type: web
    name: chat-ai
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
